# Tsakonian verb paradigm extractor

# Preparation

## Imports

In [2]:
import pandas as pd

## Raw data

In [6]:
df = pd.read_excel('../tables/verbs.xlsx').fillna('')
df.head()

,tsakonian,greek,ypot_enest,ypot_aor,orist_aor,metochi,type,source
0,αβαίνου,λαβαίνω,,,αβήκα,,,1
1,αβζ̌ύντου,"υποφέρω από δίψα, ουρλιάζω",,,αβζύα,,,1
2,αβούκ̇ου,λαβώνω,,,αβούκα,,,1
3,αγανίου,παθαίνω οξείδωση,,,αγανία,,,1
4,αγκατού,φράσσω,,,αγατήκα,,,1

# A paradigms

Verbs ending in `-ου`

In [7]:
# A1
ending = 'νου'
negative_ending = 'ούνου'

paradigm = 'Α1'
add = True
mask = (df['tsakonian'].str.endswith(ending) & ~df['tsakonian'].str.endswith(negative_ending))

if add:
    df.loc[mask, 'paradigm'] = paradigm
display(df[mask])

,tsakonian,greek,ypot_enest,ypot_aor,orist_aor,metochi,type,source,paradigm
0,αβαίνου,λαβαίνω,,,αβήκα,,,1,Α1
5,αγκραίνου,μπλέκομαι,,,αγκράκα,,,1,Α1
26,βάνου,βάζω,,,,,,1,Α1
41,δεΐνου,δένω,,,εδεήκα,,,1,Α1
43,δεχάνου,δείχνω,,,εδενά,,,1,Α1
61,καταβαίνου,καταλαβαίνω,,,,,,1,Α1
63,κατσίνου,δαγκώνω,,,εκατσίκα,,,1,Α1
66,κιάνου,πιάνω,,κιάσου,εκιάκα,κιατ̇έ,,1,Α1
70,κίνου,πίνω,κίνου,κίου,εγκίκα,γκιτέ,,1,Α1
72,κλείνου,κλείνω,,κλείου,εκλείκα,κλιστέ,,1,Α1
79,μιτσαίνου,μικραίνω,,,εμιτσ̌άγκα,,,1,Α1
81,μπαίνου,μπαίνω,μπαίνου,μπάου,εμπάκα,μπατέ,,1,Α1
82,μπαΐνου,ανεβαίνω; Βγαίνω,μπαΐνου,μπαΐου,εμπαήκα,μπαητέ,,1,Α1
83,μπάνου,βγάζω,μπάνου,μπάλου,επμαλ̣ήκα,μπαλ̣ητέ,,1,Α1
99,ξεχαίνου,ξεχνάω,,,εξεχάκα,,,1,Α1
126,τ̇αίνου,σηκώνομαι,τ̇αίνου,τ̇άου,ετ̇ακα,τ̇ατέ,,1,Α1
130,τσαφήνου,"αφήνω, ελευθερώνω",,τσαφήου,ετσαφήκα,,,1,Α1
139,φταίνου,ψήνω,,φτάου,εφτάκα,φτατέ,,1,Α1
145,χάνου,χάνω,χάνου,χάου,εχάκα,χατέ,,1,Α1
147,ψαίνου,"σφουγγίζω, σκουπίζω",,,εψάκα,,,1,Α1

In [9]:
# A2
ending = 'ούνου'
paradigm = 'Α2'

add = True
mask = (df['tsakonian'].str.endswith(ending))

if add:
    df.loc[mask, 'paradigm'] = paradigm
display(df[mask])

,tsakonian,greek,ypot_enest,ypot_aor,orist_aor,metochi,type,source,paradigm
64,κατσ̌ούνου,σπάζω,,κατσ̌ού,εκατσ̌ούκα,κατσ̌ουτέ,,1,Α2
112,ποτσούνου,φορτώνω,,,εποτσούκα,,,1,Α2
122,σούνου,"φτάνω, σώζω",,σούσου,εσούκα,σουστέ,,1,Α2

In [12]:
# A3
ending = 'ούκ̇ου'
paradigm = 'Α3'

add = True
mask = (df['tsakonian'].str.endswith(ending))

if add:
    df.loc[mask, 'paradigm'] = paradigm
display(df[mask])

,tsakonian,greek,ypot_enest,ypot_aor,orist_aor,metochi,type,source,paradigm
2,αβούκ̇ου,λαβώνω,,,αβούκα,,,1,Α3
13,ανεμούκ̇ου,πετάω,,,ανεμούκα,,,1,Α3
19,αποσούκ̇ου,"πηγαίνω, μεταφέρω",,αποσού,αποσούκα,αποσουτέ,,1,Α3
20,απρούκ̇ου,απλώνω,,απρού,απρούκα,απρουτέ,,1,Α3
34,γκιούκ̇ου,ντύνω,,γκιου,εγκιούκα,γκιουτέ,,1,Α3
74,κ̇οντούκ̇ου,κρατάω,,κ̇οντού,εκ̇οντούκα,κ̇οντουτέ,,1,Α3
77,μακούκ̇ου,μαλακώνω,,,εμακούκα,,,1,Α3
100,ξηούκ̇ου,ξηλώνω,,,εξηούκα,,,1,Α3
101,οργούκ̇ου,οργώνω,,οργού,οργούκα,οργουτέ,,1,Α3
120,σκαρμούκ̇ου,"ξαφνιάζω, τρομάζω",,,εσκαρμούκα,,,1,Α3
144,χαμεούκ̇ου,χαμηλώνω,,,εχαμεούκα,,,1,Α3

In [13]:
# A4
ending = ('ίχου', 'ίντου', 'ύντου')
paradigm = 'Α3'

add = True
mask = (df['tsakonian'].str.endswith(ending))

if add:
    df.loc[mask, 'paradigm'] = paradigm
display(df[mask])

,tsakonian,greek,ypot_enest,ypot_aor,orist_aor,metochi,type,source,paradigm
1,αβζ̌ύντου,"υποφέρω από δίψα, ουρλιάζω",,,αβζύα,,,1,Α3
9,ακίχου,αλατίζω,,,ακία,,,1,Α3
10,ακ̇ουγγίχου,ακουμπώ,,,ακ̇ουγγία,,,1,Α3
14,ανοίντου,ανοίγω,,,ανοία,,,1,Α3
46,δρανίντου,τρέχω γρήγορα,,,εδρανία,,,1,Α3
54,θυνίχου,θυμίζω,,θυνίτσου,εθυνία,θυνιτ̇έ,,1,Α3
73,κ̇ολλίχου,κολλώ,,,εκ̇ολλία,,,1,Α3
94,ντιζικίχου,"πειράζω, ενοχλώ",,,,,,1,Α3
98,ξερίχου,"ρίχνω, πετάω",,,εξερία,,,1,Α3
128,τραβίντου,τραβάω,τραβίντου,τραβίτσου,ετραβία,,,1,Α3
132,τσιταίντου,πέφτω,,,ετσιτά,,,1,Α3

In [14]:
# A5
ending = 'ζου'
paradigm = 'Α5'

add = True
mask = (df['tsakonian'].str.endswith(ending))

if add:
    df.loc[mask, 'paradigm'] = paradigm
display(df[mask])

,tsakonian,greek,ypot_enest,ypot_aor,orist_aor,metochi,type,source,paradigm
7,ακεικάζου,"συμπεραίνω, παρομοιάζω",,,ακεικά,,,1,Α5
11,αλικογκίζου,"εμποδίζω, καθυστερώ",,,αλικογκία,,,1,Α5
15,αντζάζου,ακουμοώ την πληγή και την ερεθίζω,,,αντζά,,,1,Α5
17,απογιάζου,ξεγελώ την πείνα με κάτι,,,απογιά,,,1,Α5
29,βουκ̇ιάζου,"βουτάω, αρπάζω",,,εβουκ̇ιά,,,1,Α5
58,καρδιάζου,κρυώνω,,,εκαρδιά,,,1,Α5
76,κ̇ρύζου,πλύνω,,κ̇ρύσου,εκ̇ρύα,,,1,Α5
91,νιουρίζου,γνωρίζω,νιουρίζου,νιουρίσου,ενιουρία,νιουριστέ,,1,Α5
97,ξεκάζου,κοιτάζω,,,,,,1,Α5
149,ψαχνίζου,στεγνώνω,,,εψαχνία,,,1,Α5

In [16]:
# A6
ending = 'φου'
paradigm = 'Α6'

add = True
mask = (df['tsakonian'].str.endswith(ending))

if add:
    df.loc[mask, 'paradigm'] = paradigm
display(df[mask])

,tsakonian,greek,ypot_enest,ypot_aor,orist_aor,metochi,type,source,paradigm
36,γκριούφου,κρύβω,,γκριούψου,εγκριούβα,γκριουφτέ,,1,Α6
38,γράφου,γράφω,γράφου,γράψω,εγράβα,γραφτέ,,1,Α6
71,κιούφου,κοιμάμαι,κιούφου,κιούψου,εκιούβα,κιουφτέ,,1,Α6
93,νίφου,πλένω το πρόσωπο,,,ενίβα,,,1,Α6
96,ξάφου,χτυπώ ξαφνικά,,,εξάβα,,,1,Α6
107,πάφου,"παύω,σταματάω",,,επαύα,,,1,Α6
133,τσ̌ίφου,τρίβω,,,ετσ̌ίβα,,,1,Α6

In [20]:
# A7
ending = 'έγγου'
paradigm = 'Α7'

add = True
mask = (df['tsakonian'].str.endswith(ending))

if add:
    df.loc[mask, 'paradigm'] = paradigm
display(df[mask])

,tsakonian,greek,ypot_enest,ypot_aor,orist_aor,metochi,type,source,paradigm
31,γαλέγγου,ρίχνω τον καρπό πριν ωριμάσει,,,εγαλεύα,,,1,Α7
45,δουλέγγου,δουλεύω,,δουλέψω,εδουλεύα,δουλευτέ,,2,Α7
47,έγγου,πηγαίνω,έγγου,ζάου,εζάκα,ζατέ,,1,Α7
85,μπλέγγου,διώχνω,μπλέγγου,μπλέψου,εμπλεύα,μπλευτέ,,1,Α7
86,μπλέγγου,"μπερδεύω, μπλέκω",μπλέγγου,μπλέξου,εμπλέα,μπλεχτέ,,1,Α7
118,σαλέγγου,κινούμαι,,,εσαλεύα,,,1,Α7
124,στενοχωρέγγου,στενοχωρώ,στενοχωρέγγω,στενοχωρέψου,εστενοχωρεύα,,,1,Α7

In [22]:
# A8
ending = 'ίγγου'
paradigm = 'Α8'

add = True
mask = (df['tsakonian'].str.endswith(ending))

if add:
    df.loc[mask, 'paradigm'] = paradigm
display(df[mask])

,tsakonian,greek,ypot_enest,ypot_aor,orist_aor,metochi,type,source,paradigm
115,πρίγγου,πνίγω,,πρίτσου,επρία,,,1,Α8

In [27]:
# A9
ending = 'έχου'
paradigm = 'Α9'

add = True
mask = (df['tsakonian'].str.endswith(ending))

if add:
    df.loc[mask, 'paradigm'] = paradigm
display(df[mask])

,tsakonian,greek,ypot_enest,ypot_aor,orist_aor,metochi,type,source,paradigm
30,βρέχου,βρέχω,βρέχου,βρέτσου,εβρέα,βρετ̇έ,,1,Α9
49,ερέχου,βρίσκω,,ρέσου,ερέκα,ερεστέ,,1,Α9
51,έχου,έχω,έχου,έχου,,,,1,Α9
84,μπέχου,σκεπάζω,μπέχου,μπέτσου,εμπέα,μπετέ,,1,Α9
104,παντέχου,περιμένω,,,,,,1,Α9
114,π̇ουντέχου,σβήνω,,πουντέτσου,επ̇ουντέα,,,1,Α9

In [28]:
# A10
ending = 'ίου'
paradigm = 'Α10'

add = True
mask = (df['tsakonian'].str.endswith(ending))

if add:
    df.loc[mask, 'paradigm'] = paradigm
display(df[mask])

,tsakonian,greek,ypot_enest,ypot_aor,orist_aor,metochi,type,source,paradigm
3,αγανίου,παθαίνω οξείδωση,,,αγανία,,,1,Α10
6,ακαλίου,κυλώ,,,ακαλίκα,,,1,Α10
44,δίου,δίνω,δίνου,δου,εδούκα,δουτέ,,1,Α10
60,κασίου,κοιμάμαι,,,,,,1,Α10
62,κ̇ατίου,τοποθετώ,,,εκ̇ατίκα,,,1,Α10
90,νίου,ακούω,νίνου,νιάου,ενιάκα,νιατέ,,1,Α10
95,ντίου,χτυπώ,ντίνου,ντου,εντούκα,ντουτέ,,1,Α10
106,παρίου,έρχομαι,παρίμα,μόλου,εκάνα,φερτέ,,1,Α10
110,ποίου,κάνω,ποίνου,ποίου,εμπήκα,μποιτέ,,1,Α10
119,σαπρίου,σαπίζω,,,εσαπρία,,,1,Α10
141,φταίου,φταίω,,,εφταίκα,,,1,Α10

In [33]:
# A11
ending = 'αίσου'
paradigm = 'Α11'

add = True
mask = (df['tsakonian'].str.endswith(ending))

if add:
    df.loc[mask, 'paradigm'] = paradigm
display(df[mask])

   tsakonian greek ypot_enest ypot_aor orist_aor metochi type  source paradigm
40    δαίσου  καίω     δαίσου     δάου     εδάκα                    1      Α11

In [31]:
# A12
ending = 'ρίκ̇ου'
paradigm = 'Α12'

add = True
mask = (df['tsakonian'].str.endswith(ending))

if add:
    df.loc[mask, 'paradigm'] = paradigm
display(df[mask])

,tsakonian,greek,ypot_enest,ypot_aor,orist_aor,metochi,type,source,paradigm
22,αρίκ̇ου,παίρνω,,άρου,άγκα,παρτέ,,1,Α12
57,καραφερίκ̇ου,καταφέρνω,,,εκατανέγκα,,,1,Α12

In [32]:
# A13
ending = 'ρου'
paradigm = 'Α13'

add = True
mask = (df['tsakonian'].str.endswith(ending))

if add:
    df.loc[mask, 'paradigm'] = paradigm
display(df[mask])

,tsakonian,greek,ypot_enest,ypot_aor,orist_aor,metochi,type,source,paradigm
32,γείρου,επιστρέφω,,,εγείρκα,,,1,Α13
42,δέρου,"δέρνω, χτυπώ",,,εδάρκα,,,1,Α13

In [34]:
# A14
ending = 'άσσου'
paradigm = 'Α14'

add = True
mask = (df['tsakonian'].str.endswith(ending))

if add:
    df.loc[mask, 'paradigm'] = paradigm
display(df[mask])

,tsakonian,greek,ypot_enest,ypot_aor,orist_aor,metochi,type,source,paradigm
25,άσσου,αλλάζω,,,α/εά,,,1,Α14
111,ποτάσσου,φτουράω,,,εποτά,,,1,Α14