# Tsakonian verb paradigm extractor

# Preparation

## Imports

In [22]:
import pandas as pd

## Raw data

In [23]:
df = pd.read_excel('../tables/verbs.xlsx').fillna('')
df.head()

,tsakonian,greek,ypot_enest,ypot_aor,orist_aor,metochi,source
0,αβαίνου,λαβαίνω,,,αβήκα,,1
1,αβζ̌ύντου,"υποφέρω από δίψα, ουρλιάζω",,,αβζύα,,1
2,αβούκ̇ου,λαβώνω,,,αβούκα,,1
3,αγανίου,παθαίνω οξείδωση,,,αγανία,,1
4,αγκατού,φράσσω,,,αγατήκα,,1

# A paradigms

Verbs ending in `-ου`

In [24]:
# A1
ending = 'νου'
negative_ending = 'ούνου'

paradigm = 'Α1'
add = True
mask = (df['tsakonian'].str.endswith(ending) & ~df['tsakonian'].str.endswith(negative_ending))

if add:
    df.loc[mask, 'paradigm'] = paradigm
display(df[mask])

,tsakonian,greek,ypot_enest,ypot_aor,orist_aor,metochi,source,paradigm
0,αβαίνου,λαβαίνω,,,αβήκα,,1,Α1
5,αγκραίνου,μπλέκομαι,,,αγκράκα,,1,Α1
26,βάνου,βάζω,,,,,1,Α1
41,δεΐνου,δένω,,,εδεήκα,,1,Α1
43,δεχάνου,δείχνω,,,εδενά,,1,Α1
61,καταβαίνου,καταλαβαίνω,,,,,1,Α1
63,κατσίνου,δαγκώνω,,,εκατσίκα,,1,Α1
66,κιάνου,πιάνω,,κιάσου,εκιάκα,κιατ̇έ,1,Α1
70,κίνου,πίνω,κίνου,κίου,εγκίκα,γκιτέ,1,Α1
72,κλείνου,κλείνω,,κλείου,εκλείκα,κλιστέ,1,Α1
79,μιτσαίνου,μικραίνω,,,εμιτσ̌άγκα,,1,Α1
81,μπαίνου,μπαίνω,μπαίνου,μπάου,εμπάκα,μπατέ,1,Α1
82,μπαΐνου,ανεβαίνω; Βγαίνω,μπαΐνου,μπαΐου,εμπαήκα,μπαητέ,1,Α1
83,μπάνου,βγάζω,μπάνου,μπάλου,επμαλ̣ήκα,μπαλ̣ητέ,1,Α1
99,ξεχαίνου,ξεχνάω,,,εξεχάκα,,1,Α1
126,τ̇αίνου,σηκώνομαι,τ̇αίνου,τ̇άου,ετ̇ακα,τ̇ατέ,1,Α1
130,τσαφήνου,"αφήνω, ελευθερώνω",,τσαφήου,ετσαφήκα,,1,Α1
139,φταίνου,ψήνω,,φτάου,εφτάκα,φτατέ,1,Α1
145,χάνου,χάνω,χάνου,χάου,εχάκα,χατέ,1,Α1
147,ψαίνου,"σφουγγίζω, σκουπίζω",,,εψάκα,,1,Α1

In [25]:
# A2
ending = 'ούνου'
paradigm = 'Α2'

add = True
mask = (df['tsakonian'].str.endswith(ending))

if add:
    df.loc[mask, 'paradigm'] = paradigm
display(df[mask])

,tsakonian,greek,ypot_enest,ypot_aor,orist_aor,metochi,source,paradigm
64,κατσ̌ούνου,σπάζω,,κατσ̌ού,εκατσ̌ούκα,κατσ̌ουτέ,1,Α2
112,ποτσούνου,φορτώνω,,,εποτσούκα,,1,Α2
122,σούνου,"φτάνω, σώζω",,σούσου,εσούκα,σουστέ,1,Α2

In [26]:
# A3
ending = 'ούκ̇ου'
paradigm = 'Α3'

add = True
mask = (df['tsakonian'].str.endswith(ending))

if add:
    df.loc[mask, 'paradigm'] = paradigm
display(df[mask])

,tsakonian,greek,ypot_enest,ypot_aor,orist_aor,metochi,source,paradigm
2,αβούκ̇ου,λαβώνω,,,αβούκα,,1,Α3
13,ανεμούκ̇ου,πετάω,,,ανεμούκα,,1,Α3
19,αποσούκ̇ου,"πηγαίνω, μεταφέρω",,αποσού,αποσούκα,αποσουτέ,1,Α3
20,απρούκ̇ου,απλώνω,,απρού,απρούκα,απρουτέ,1,Α3
34,γκιούκ̇ου,ντύνω,,γκιου,εγκιούκα,γκιουτέ,1,Α3
74,κ̇οντούκ̇ου,κρατάω,,κ̇οντού,εκ̇οντούκα,κ̇οντουτέ,1,Α3
77,μακούκ̇ου,μαλακώνω,,,εμακούκα,,1,Α3
100,ξηούκ̇ου,ξηλώνω,,,εξηούκα,,1,Α3
101,οργούκ̇ου,οργώνω,,οργού,οργούκα,οργουτέ,1,Α3
120,σκαρμούκ̇ου,"ξαφνιάζω, τρομάζω",,,εσκαρμούκα,,1,Α3
144,χαμεούκ̇ου,χαμηλώνω,,,εχαμεούκα,,1,Α3

In [27]:
# A4
ending = ('ίχου', 'ίντου', 'ύντου', 'άντου')
paradigm = 'Α4`'

add = True
mask = (df['tsakonian'].str.endswith(ending))

if add:
    df.loc[mask, 'paradigm'] = paradigm
display(df[mask])

,tsakonian,greek,ypot_enest,ypot_aor,orist_aor,metochi,source,paradigm
1,αβζ̌ύντου,"υποφέρω από δίψα, ουρλιάζω",,,αβζύα,,1,Α4`
9,ακίχου,αλατίζω,,,ακία,,1,Α4`
10,ακ̇ουγγίχου,ακουμπώ,,,ακ̇ουγγία,,1,Α4`
14,ανοίντου,ανοίγω,,,ανοία,,1,Α4`
46,δρανίντου,τρέχω γρήγορα,,,εδρανία,,1,Α4`
54,θυνίχου,θυμίζω,,θυνίτσου,εθυνία,θυνιτ̇έ,1,Α4`
73,κ̇ολλίχου,κολλώ,,,εκ̇ολλία,,1,Α4`
94,ντιζικίχου,"πειράζω, ενοχλώ",,,,,1,Α4`
98,ξερίχου,"ρίχνω, πετάω",,,εξερία,,1,Α4`
128,τραβίντου,τραβάω,τραβίντου,τραβίτσου,ετραβία,,1,Α4`
132,τσιταίντου,πέφτω,,,ετσιτά,,1,Α4`
152,φωνιάντου,φωνάζω,φωνιάντου,φωνιάτσου,εφωνιά,φωνιατ̇έ,1,Α4`

In [28]:
# A5
ending = 'ζου'
paradigm = 'Α5'

add = True
mask = (df['tsakonian'].str.endswith(ending))

if add:
    df.loc[mask, 'paradigm'] = paradigm
display(df[mask])

,tsakonian,greek,ypot_enest,ypot_aor,orist_aor,metochi,source,paradigm
7,ακεικάζου,"συμπεραίνω, παρομοιάζω",,,ακεικά,,1,Α5
11,αλικογκίζου,"εμποδίζω, καθυστερώ",,,αλικογκία,,1,Α5
15,αντζάζου,ακουμοώ την πληγή και την ερεθίζω,,,αντζά,,1,Α5
17,απογιάζου,ξεγελώ την πείνα με κάτι,,,απογιά,,1,Α5
29,βουκ̇ιάζου,"βουτάω, αρπάζω",,,εβουκ̇ιά,,1,Α5
58,καρδιάζου,κρυώνω,,,εκαρδιά,,1,Α5
76,κ̇ρύζου,πλύνω,,κ̇ρύσου,εκ̇ρύα,,1,Α5
91,νιουρίζου,γνωρίζω,νιουρίζου,νιουρίσου,ενιουρία,νιουριστέ,1,Α5
97,ξεκάζου,κοιτάζω,,,,,1,Α5
149,ψαχνίζου,στεγνώνω,,,εψαχνία,,1,Α5

In [29]:
# A6
ending = 'φου'
paradigm = 'Α6'

add = True
mask = (df['tsakonian'].str.endswith(ending))

if add:
    df.loc[mask, 'paradigm'] = paradigm
display(df[mask])

,tsakonian,greek,ypot_enest,ypot_aor,orist_aor,metochi,source,paradigm
36,γκριούφου,κρύβω,,γκριούψου,εγκριούβα,γκριουφτέ,1,Α6
38,γράφου,γράφω,γράφου,γράψω,εγράβα,γραφτέ,1,Α6
71,κιούφου,κοιμάμαι,κιούφου,κιούψου,εκιούβα,κιουφτέ,1,Α6
93,νίφου,πλένω το πρόσωπο,,,ενίβα,,1,Α6
96,ξάφου,χτυπώ ξαφνικά,,,εξάβα,,1,Α6
107,πάφου,"παύω,σταματάω",,,επαύα,,1,Α6
133,τσ̌ίφου,τρίβω,,,ετσ̌ίβα,,1,Α6

In [30]:
# A7
ending = 'έγγου'
paradigm = 'Α7'

add = True
mask = (df['tsakonian'].str.endswith(ending))

if add:
    df.loc[mask, 'paradigm'] = paradigm
display(df[mask])

,tsakonian,greek,ypot_enest,ypot_aor,orist_aor,metochi,source,paradigm
31,γαλέγγου,ρίχνω τον καρπό πριν ωριμάσει,,,εγαλεύα,,1,Α7
45,δουλέγγου,δουλεύω,,δουλέψω,εδουλεύα,δουλευτέ,2,Α7
47,έγγου,πηγαίνω,έγγου,ζάου,εζάκα,ζατέ,1,Α7
85,μπλέγγου,διώχνω,μπλέγγου,μπλέψου,εμπλεύα,μπλευτέ,1,Α7
86,μπλέγγου,"μπερδεύω, μπλέκω",μπλέγγου,μπλέξου,εμπλέα,μπλεχτέ,1,Α7
118,σαλέγγου,κινούμαι,,,εσαλεύα,,1,Α7
124,στενοχωρέγγου,στενοχωρώ,στενοχωρέγγω,στενοχωρέψου,εστενοχωρεύα,,1,Α7

In [31]:
# A8
ending = 'ίγγου'
paradigm = 'Α8'

add = True
mask = (df['tsakonian'].str.endswith(ending))

if add:
    df.loc[mask, 'paradigm'] = paradigm
display(df[mask])

    tsakonian  greek ypot_enest ypot_aor orist_aor metochi  source paradigm
115   πρίγγου  πνίγω             πρίτσου     επρία               1       Α8

In [32]:
# A9
ending = 'έχου'
paradigm = 'Α9'

add = True
mask = (df['tsakonian'].str.endswith(ending))

if add:
    df.loc[mask, 'paradigm'] = paradigm
display(df[mask])

,tsakonian,greek,ypot_enest,ypot_aor,orist_aor,metochi,source,paradigm
30,βρέχου,βρέχω,βρέχου,βρέτσου,εβρέα,βρετ̇έ,1,Α9
49,ερέχου,βρίσκω,,ρέσου,ερέκα,ερεστέ,1,Α9
51,έχου,έχω,έχου,έχου,,,1,Α9
84,μπέχου,σκεπάζω,μπέχου,μπέτσου,εμπέα,μπετέ,1,Α9
104,παντέχου,περιμένω,,,,,1,Α9
114,π̇ουντέχου,σβήνω,,πουντέτσου,επ̇ουντέα,,1,Α9

In [33]:
# A10
ending = 'ίου'
paradigm = 'Α10'

add = True
mask = (df['tsakonian'].str.endswith(ending))

if add:
    df.loc[mask, 'paradigm'] = paradigm
display(df[mask])

,tsakonian,greek,ypot_enest,ypot_aor,orist_aor,metochi,source,paradigm
3,αγανίου,παθαίνω οξείδωση,,,αγανία,,1,Α10
6,ακαλ̣ίου,κυλώ,ακαλ̣ήνου,ακαλ̣ίου,ακαλ̣ίκα,,1,Α10
44,δίου,δίνω,δίνου,δου,εδούκα,δουτέ,1,Α10
60,κασίου,κοιμάμαι,,,,,1,Α10
62,κ̇ατίου,τοποθετώ,,,εκ̇ατίκα,,1,Α10
90,νίου,ακούω,νίνου,νιάου,ενιάκα,νιατέ,1,Α10
95,ντίου,χτυπώ,ντίνου,ντου,εντούκα,ντουτέ,1,Α10
106,παρίου,έρχομαι,παρίμα,μόλου,εκάνα,φερτέ,1,Α10
110,ποίου,κάνω,ποίνου,ποίου,εμπήκα,μποιτέ,1,Α10
119,σαπρίου,σαπίζω,,,εσαπρία,,1,Α10
141,φταίου,φταίω,,,εφταίκα,,1,Α10

In [34]:
# A11
ending = 'αίσου'
paradigm = 'Α11'

add = True
mask = (df['tsakonian'].str.endswith(ending))

if add:
    df.loc[mask, 'paradigm'] = paradigm
display(df[mask])

   tsakonian greek ypot_enest ypot_aor orist_aor metochi  source paradigm
40    δαίσου  καίω     δαίσου     δάου     εδάκα               1      Α11

In [35]:
# A12
ending = 'ρίκ̇ου'
paradigm = 'Α12'

add = True
mask = (df['tsakonian'].str.endswith(ending))

if add:
    df.loc[mask, 'paradigm'] = paradigm
display(df[mask])

,tsakonian,greek,ypot_enest,ypot_aor,orist_aor,metochi,source,paradigm
22,αρίκ̇ου,παίρνω,,άρου,άγκα,παρτέ,1,Α12
57,καραφερίκ̇ου,καταφέρνω,,,εκατανέγκα,,1,Α12

In [36]:
# A13
ending = 'ρου'
paradigm = 'Α13'

add = True
mask = (df['tsakonian'].str.endswith(ending))

if add:
    df.loc[mask, 'paradigm'] = paradigm
display(df[mask])

,tsakonian,greek,ypot_enest,ypot_aor,orist_aor,metochi,source,paradigm
32,γείρου,επιστρέφω,,,εγείρκα,,1,Α13
42,δέρου,"δέρνω, χτυπώ",,,εδάρκα,,1,Α13

In [37]:
# A14
ending = 'άσσου'
paradigm = 'Α14'

add = True
mask = (df['tsakonian'].str.endswith(ending))

if add:
    df.loc[mask, 'paradigm'] = paradigm
display(df[mask])

    tsakonian    greek ypot_enest ypot_aor orist_aor metochi  source paradigm
25      άσσου   αλλάζω                          α/εά               1      Α14
111  ποτάσσου  φτουράω                         εποτά               1      Α14
151   αράσσου   αράσσω    αράσσου  αράτσου       αρά               2      Α14

# Β paradigms

Verbs ending in `-ού`

In [38]:
# Β1
ending = 'ού'
aoristos_ending = 'άκα'
paradigm = 'Β1'

add = True
mask = (df['tsakonian'].str.endswith(ending) & 
        df['orist_aor'].str.endswith(aoristos_ending))

if add:
    df.loc[mask, 'paradigm'] = paradigm
display(df[mask])

,tsakonian,greek,ypot_enest,ypot_aor,orist_aor,metochi,source,paradigm
21,αραμού,"μένω, κατοικώ",,αραμάου,αραμάκα,αραματέ,1,Β1
28,βού,κλαίω,βούνου,βάτσου,εβάκα,,1,Β1
33,γεού,γελάω,γελ̣ήνου,γιάου,εγιάκα,,1,Β1
68,κιμού,τιμώ,,,εκιμάκα,,1,Β1
80,μοζού,πονάω,μοζήνου,μοζάου,εμοζάκα,μοζαΐχου,1,Β1
102,ορού,βλέπω,ορήνου,οράου,οράκα,ορατέ,1,Β1
109,περού,περνώ,περήνου,περάου,επεράκα,περατέ,1,Β1
138,φουσού,φυσάω,φουσήνου,φουσάου,εφουσάκα,,1,Β1
146,χαού,χαλάω,χαλ̣ήνου,χάου,εχάκα,χαρέ,1,Β1

In [39]:
# Β2
ending = 'ού'
aoristos_ending = 'ήκα'
paradigm = 'Β2'

add = True
mask = (df['tsakonian'].str.endswith(ending) & 
        df['orist_aor'].str.endswith(aoristos_ending))

if add:
    df.loc[mask, 'paradigm'] = paradigm
display(df[mask])

,tsakonian,greek,ypot_enest,ypot_aor,orist_aor,metochi,source,paradigm
4,αγκατού,φράσσω,,,αγατήκα,,1,Β2
12,αμογού,ομολογώ,,,αμογήκα,,1,Β2
23,αρού,αρμέγω,αρήνου,αρήου,αρήκα,αρητέ,1,Β2
24,ασού,σουρώνω,,,ασήκα,,1,Β2
27,βογού,ευλογώ,,,βογήκα,,1,Β2
52,ζυρογού,βρωμοκοπάω,,,εζυρογήκα,,1,Β2
75,κουβαού,κουβαλώ,,,εκουβαλ̣ήκα,,1,Β2
78,μετσ̌ού,μετρώ,,,εμετσ̌ήκα,,1,Β2
89,νιού,μηλάω,νιλ̣ήνου,νιλ̣ήου,ενιλ̣ήκα,νιλ̣ητέ,1,Β2
117,ρωτού,ρωτάω,ρωτήνου,ρωτήου,ερωτήκα,ρωτητέ,1,Β2
135,τσ̌υγού,τρυγώ,,,εστσ̌υγήκα,,1,Β2
148,ψαφού,ψάχνω,ψαφήνου,ψαφήου,εψαφήκα,ψαφητέ,1,Β2
150,νικού,νικώ,,νιτζήου,ενιτζήκα,,2,Β2

In [40]:
# Β3
ending = 'ού'
aoristos_ending = 'έκα'
paradigm = 'Β3'

add = True
mask = (df['tsakonian'].str.endswith(ending) & 
        df['orist_aor'].str.endswith(aoristos_ending))

if add:
    df.loc[mask, 'paradigm'] = paradigm
display(df[mask])

,tsakonian,greek,ypot_enest,ypot_aor,orist_aor,metochi,source,paradigm
16,αού,λέω,αλήνου,αλήου,επέκα,πετέ,1,Β3
69,κιμωρού,τιμωρώ,,,εκιμωρέκα,,1,Β3
87,μπορού,μπορώ,,μπορέου,εμπορέκα,,1,Β3
105,παραθαρρού,χαλαρώνω την προσοχή μου,,,επαραθαρρέκα,,1,Β3
137,φορού,φοράω,φορήνου,φορέου,εφορέκα,φορεστέ,1,Β3

# Γ paradigms: passive voices

In [41]:
# Γ
ending = 'ε'
paradigm = 'Γ'

add = True
mask = (df['tsakonian'].str.endswith(ending))

if add:
    df.loc[mask, 'paradigm'] = paradigm
display(df[mask])

,tsakonian,greek,ypot_enest,ypot_aor,orist_aor,metochi,source,paradigm
8,ακισταινούμενε,κουράζομαι,,,ακιστάμα,,1,Γ
35,γκιουκ̇ούμενε,ντύνομαι,,γκιουθού,εγκιούμα,γκιουτέ,1,Γ
37,γκριουφούμενε,γκριουφτού,,γκριουφτού,εγκριούμα,γκριουφτέ,1,Γ
39,γραφούμενε,γράφομαι,γραφούμα,γραφτού,εγράμμα,γραφτέ,1,Γ
50,ερικ̇ούμενε,βρίσκομαι,,ρεστού,ερέσια,,1,Γ
53,θυμούμενε,θυμάμαι,,θυνηθού,εθυνήμα,,1,Γ
59,κασημένε,κάθομαι,κασήμα,κατσάου,εκατσάκα,κατσατέ,1,Γ
67,κιανούμενε,πιάνομαι,,κιατ̇ού,εκιάμα,κιατ̇έ,1,Γ
92,νιουρισκούμενε,γνωρίζομαι,νιουρισκούμα,νιουριστού,ενιουρίσμα,νιουριστέ,1,Γ
103,ορούμενε,φαίνομαι,ορινούμα,οραθού,οράμα,ορατέ,1,Γ
116,ρωτηκ̇ούμενε,ρωτιέμαι,ρωτηκ̇ούμα,ρωτηθού,ερωτήμα,ρωτητέ,1,Γ
123,σουσκούμενε,τελειώνω,,σουστού,εσούσμα,σουστέ,1,Γ
125,στενοχωρεγγούμενε,στεναχωριέμαι,στενοχωρεγγούμα,στενοχωρευτού,εστενοχωρέμα,,1,Γ
129,τραβιντούμενε,τραβιέμαι,τραβιντούμα,τραβιτ̇ού,ετραβίμα,τραβιτ̇έ,1,Γ
140,φταινούμενε,ψήνομαι,,φταθού,εφτάμα,φτατέ,1,Γ
143,φωνιαντούμενε,φωνάζομαι,φωνιαντούμα,φωνιατ̇ού,εφωνιάμα,φωνιατ̇έ,1,Γ

# Unorganized verbs

In [42]:
# Extract verbs where the paradigm is empty
df[df['paradigm'].isnull()]

,tsakonian,greek,ypot_enest,ypot_aor,orist_aor,metochi,source,paradigm
18,αποού,στέλνω,,,απολ̣ύκα,,1,NaN
48,ένι,είμαι,ένι,ένι,έμα,,1,NaN
55,κ̇ακ̇ούχου,"χώνω, έχωσα",,,εκ̇ακ̇ούα,,1,NaN
56,κάμου,"καματεύω, σπέρνω",,καμέου,εκαμεκα,,1,NaN
65,κεινού,πεινάω,,κεινάου,εκείνακα,κεινατέ,1,NaN
88,νέμου,βοσκώ,νέμου,νεμάου,ενεμάκα,νεματέ,1,NaN
108,πενάκ̇ου,πεθαίνω,,πεθάνου,επενάκα,πενατέ,1,NaN
113,που,πουλάω,πουλ̣ήνου,πουλ̣ήου,επουλ̣ήκα,,1,NaN
121,σκωρού,συγχωρώ,,,εσκουγκία,,1,NaN
127,τ̇αΐχου,σηκώνω,τ̇αΐχου,τ̇αΐσου,ετ̇αΐα,τ̇αΐστέ,1,NaN
131,τσ̌άχου,τρέχω,τσ̌αχου,τσ̌αχίτσου,ετσ̌αχήκα,,1,NaN
134,τσ̌ου,τρώω,τσ̌ούνου,φάου,εφαήκα,φαητέ,1,NaN
136,φοζαΐχου,φοβίζω,,,εφοζαΐα,,1,NaN
142,φύου,φεύγω,φύνου,φύτσου,εφύγκα,,1,NaN